#version 460 core

#define PI 3.14159265359

layout(local_size_x = 16, local_size_y = 16) in;

struct Camera
{
    vec4 position;
    mat4 viewMatrix;
    mat4 projectionMatrix;
    mat4 viewProjectionMatrix;
};

struct DirectionLight
{
    vec4 direction;
    vec4 color;
};

layout(set = 0, binding = 0) uniform SceneData
{
	DirectionLight light;
	Camera camera;
} sceneData;

layout( set = 1, binding = 0) uniform sampler2D albedo;
layout( set = 1, binding = 1) uniform sampler2D position;
layout( set = 1, binding = 2) uniform sampler2D normal;
layout( set = 1, binding = 3) uniform sampler2D metalRoughness;
layout( set = 1, binding = 4, rgba32f) uniform image2D outTexture;

float DistributionGGX(vec3 N, vec3 H, float roughness)
{
    float a = roughness*roughness;
    float a2 = a*a;
    float NdotH = max(dot(N, H), 0.0);
    float NdotH2 = NdotH*NdotH;

    float nom   = a2;
    float denom = (NdotH2 * (a2 - 1.0) + 1.0);
    denom = PI * denom * denom;

    return nom / denom;
}
// ----------------------------------------------------------------------------
float GeometrySchlickGGX(float NdotV, float roughness)
{
    float r = (roughness + 1.0);
    float k = (r*r) / 8.0;

    float nom   = NdotV;
    float denom = NdotV * (1.0 - k) + k;

    return nom / denom;
}
// ----------------------------------------------------------------------------
float GeometrySmith(vec3 N, vec3 V, vec3 L, float roughness)
{
    float NdotV = max(dot(N, V), 0.0);
    float NdotL = max(dot(N, L), 0.0);
    float ggx2 = GeometrySchlickGGX(NdotV, roughness);
    float ggx1 = GeometrySchlickGGX(NdotL, roughness);

    return ggx1 * ggx2;
}
// ----------------------------------------------------------------------------
vec3 fresnelSchlick(float cosTheta, vec3 F0)
{
    return F0 + (1.0 - F0) * pow(clamp(1.0 - cosTheta, 0.0, 1.0), 5.0);
}

void main()
{
    ivec2 grid = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outTexture);
    if(grid.x <= size.x && grid.y <= size.y)
    {
        vec2 uv = vec2(grid) / vec2(size);
        //vec4 c = texture(albedo, uv);
        //imageStore(outTexture, grid, c);

        vec3 pos = texture(position, uv).xyz;
        vec3 albedoColor = texture(albedo, uv).rgb;

        vec3 n = normalize(texture(normal, uv).xyz);
	    vec3 l = normalize(sceneData.light.direction.xyz);
        vec3 v = normalize(sceneData.camera.position.xyz - pos);
	    vec3 h = normalize(l + v);

        //vec3 n = normalize(vNormal);

        vec4 metalRoughess = texture(metalRoughness, uv);
        float metal = metalRoughess.r;
        float roughness = metalRoughess.g;

        vec3 F0 = vec3(0.04);
	    F0 = mix(F0, albedoColor, metal);

	    float NDF = DistributionGGX(n, h, roughness);   
	    float G   = GeometrySmith(n, v, l, roughness);      
	    vec3  F   = fresnelSchlick(max(dot(h, v), 0.0), F0);
	       
	    vec3 numerator    = NDF * G * F; 
	    float denominator = 4.0 * max(dot(n, v), 0.0) * max(dot(n, l), 0.0) + 0.0001; // + 0.0001 to prevent divide by zero
	    vec3 specular = numerator / denominator;

	    vec3 Ks = F;
	    vec3 Kd = vec3(1.0) - Ks;
	    Kd *= (1.0 - metal);
	    float NdotL = max(dot(n, l), 0.0);

        //TODO SSAO
        float ambientOcclusion = 1.0f;

	    vec3 ao = vec3(0.3) * sceneData.light.color.rgb * albedoColor * ambientOcclusion;
        vec4 fragColor = vec4(0.0, 0.0, 0.0, 1.0);
	    fragColor.rgb = (Kd * albedoColor / PI + specular) * NdotL * sceneData.light.color.rgb + ao;
	    fragColor.a = 1.0;
        imageStore(outTexture, grid, fragColor);
    }
}