#version 460 core

layout (local_size_x = 16, local_size_y = 16) in;

layout (set = 0, binding = 0, rgba32f) uniform image2D imageOut;

void main()
{
	ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(imageOut);
	if(pixelCoord.x < size.x && pixelCoord.y < size.y)
	{
		vec4 color = vec4(0.0, 0.0, 0.0, 1.0);
		if(gl_LocalInvocationID.x !=0 && gl_LocalInvocationID.y != 0)
		{
			color.x = float(pixelCoord.x) / float(size.x);
			color.y = float(pixelCoord.y) / float(size.y);
		}
		imageStore(imageOut, pixelCoord, color);
	}
}