#version 460 core

layout (local_size_x = 16, local_size_y = 16) in;

layout (set = 0, binding = 0, rgba32f) uniform image2D screenImage;

void main()
{
	ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(screenImage);
	vec4 color = imageLoad(screenImage, pixelCoord);
	float gray = dot(color.rgb, vec3(0.299, 0.587, 0.114));
	imageStore(screenImage, pixelCoord, vec4(gray, gray, gray, 1.0));
}